const int mimeTypeCount = 172;
char *mimeExtensions[] = { "ez", "mus", "etf", "fxt", "ftm", "hqx", "cpt",
		"doc", "bin", "dms", "lha", "lzh", "exe", "class", "w02", "w03", "w04",
		"cab", "jar", "dzl", "oda", "pdf", "ai", "eps", "ps", "smi", "smil",
		"mif", "xls", "csv", "ppt", "ppz", "pps", "pot", "wbxml", "wmlc",
		"wmlsc", "bcpio", "vcd", "pgn", "Z", "cpio", "csh", "dcr", "dir",
		"dxr", "dvi", "spl", "gtar", "gz", "hdf", "css", "js", "skp", "skd",
		"skt", "skm", "latex", "wmz", "wmd", "nc", "cdf", "sh", "shar", "swf",
		"sit", "sv4cpio", "sv4crc", "tar", "tcl", "tex", "texinfo", "texi",
		"t", "tr", "roff", "man", "me", "ms", "ustar", "src", "xml", "dtd",
		"xsl", "ent", "cat", "sty", "zip", "au", "snd", "mid", "midi", "kar",
		"mpga", "mp2", "mp3", "aif", "aiff", "aifc", "wma", "wax", "ram", "rm",
		"rpm", "ra", "wav", "pdb", "xyz", "bmp", "gif", "ief", "jpeg", "jpg",
		"jpe", "png", "tiff", "tif", "wbmp", "ras", "fh4", "fh7", "fh5", "fhc",
		"fh", "pnm", "pbm", "pgm", "ppm", "rgb", "xbm", "xpm", "xwd", "igs",
		"iges", "msh", "mesh", "silo", "wrl", "vrml", "html", "htm", "asc",
		"txt", "rtx", "rtf", "sgml", "sgm", "tsv", "wml", "wmls", "etx", "xml",
		"mpeg", "mpg", "mpe", "asf", "asx", "wm", "wmv", "wmx", "wvx", "qt",
		"mov", "avi", "movie", "ice", "3dmf", "3dm", "qd3d", "qd3", "wrl",
		"vrml", "" };

char *mimeTypes[] = { "application/andrew-inset", "application/finale",
		"application/finale", "application/finale", "application/finale",
		"application/mac-binhex40", "application/mac-compactpro",
		"application/msword", "application/octet-stream",
		"application/octet-stream", "application/octet-stream",
		"application/octet-stream", "application/octet-stream",
		"application/octet-stream", "application/octet-stream",
		"application/octet-stream", "application/octet-stream",
		"application/octet-stream", "application/octet-stream",
		"application/octet-stream", "application/oda", "application/pdf",
		"application/postscript", "application/postscript",
		"application/postscript", "application/smil", "application/smil",
		"application/vnd.mif", "application/vnd.ms-excel",
		"application/vnd.ms-excel", "application/vnd.ms-powerpoint",
		"application/vnd.ms-powerpoint", "application/vnd.ms-powerpoint",
		"application/vnd.ms-powerpoint", "application/vnd.wap.wbxml",
		"application/vnd.wap.wmlc", "application/vnd.wap.wmlscriptc",
		"application/x-bcpio", "application/x-cdlink",
		"application/x-chess-pgn", "application/x-compress",
		"application/x-cpio", "application/x-csh", "application/x-director",
		"application/x-director", "application/x-director",
		"application/x-dvi", "application/x-futuresplash",
		"application/x-gtar", "application/x-gzip", "application/x-hdf",
		"application/x-ilinc-pointplus", "application/x-javascript",
		"application/x-koan", "application/x-koan", "application/x-koan",
		"application/x-koan", "application/x-latex", "application/x-ms-wmz",
		"application/x-ms-wmd", "application/x-netcdf", "application/x-netcdf",
		"application/x-sh", "application/x-shar",
		"application/x-shockwave-flash", "application/x-stuffit",
		"application/x-sv4cpio", "application/x-sv4crc", "application/x-tar",
		"application/x-tcl", "application/x-tex", "application/x-texinfo",
		"application/x-texinfo", "application/x-troff", "application/x-troff",
		"application/x-troff", "application/x-troff-man",
		"application/x-troff-me", "application/x-troff-ms",
		"application/x-ustar", "application/x-wais-source", "application/xml",
		"application/xml", "application/xml", "application/xml",
		"application/xml", "application/xml", "application/zip", "audio/basic",
		"audio/basic", "audio/midi", "audio/midi", "audio/midi", "audio/mpeg",
		"audio/mpeg", "audio/mpeg", "audio/x-aiff", "audio/x-aiff",
		"audio/x-aiff", "audio/x-ms-wma", "audio/x-ms-wax",
		"audio/x-pn-realaudio", "audio/x-pn-realaudio",
		"audio/x-pn-realaudio-plugin", "audio/x-realaudio", "audio/x-wav",
		"chemical/x-pdb", "chemical/x-xyz", "image/bmp", "image/gif",
		"image/ief", "image/jpeg", "image/jpeg", "image/jpeg", "image/png",
		"image/tiff", "image/tiff", "image/vnd.wap.wbmp", "image/x-cmu-raster",
		"image/x-freehand", "image/x-freehand", "image/x-freehand",
		"image/x-freehand", "image/x-freehand", "image/x-portable-anymap",
		"image/x-portable-bitmap", "image/x-portable-graymap",
		"image/x-portable-pixmap", "image/x-rgb", "image/x-xbitmap",
		"image/x-xpixmap", "image/x-xwindowdump", "model/iges", "model/iges",
		"model/mesh", "model/mesh", "model/mesh", "model/vrml", "model/vrml",
		"text/html", "text/html", "text/plain", "text/plain", "text/richtext",
		"text/rtf", "text/sgml", "text/sgml", "text/tab-separated-values",
		"text/vnd.wap.wml", "text/vnd.wap.wmlscript", "text/x-setext",
		"text/xml", "video/mpeg", "video/mpeg", "video/mpeg", "video/x-ms-asf",
		"video/x-ms-asf", "video/x-ms-wm", "video/x-ms-wmv", "video/x-ms-wmx",
		"video/x-ms-wvx", "video/quicktime", "video/quicktime",
		"video/x-msvideo", "video/x-sgi-movie", "x-conference/x-cooltalk",
		"x-world/x-3dmf", "x-world/x-3dmf", "x-world/x-3dmf", "x-world/x-3dmf",
		"x-world/x-vrml", "x-world/x-vrml", "application/octet-stream" };
